[package]
name = "elm-json"
version = "0.2.7"
authors = ["ilias <mail@ilias.xyz>"]
edition = "2018"

[dependencies]
indexmap = "1"
itertools = "0.9"
failure = "0.1"
petgraph = "0.5"
slog = { version = "2", features = ["max_level_trace", "release_max_level_debug"] }
textwrap = "0.11"
bincode = "1.2.1"
slog-term = "2.5.0"
slog-async = "2.5.0"
serde  = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.1"
colored = "1.9"
dialoguer = "0.6"
dirs = "2.0"
fs2 = "0.4"
isahc = "0.9"

[dev-dependencies]
assert_cmd = "0.11"
assert_fs = "0.11"
predicates = "1"

[lib]
name = "elm_json"
path = "src/lib/lib.rs"

[[bin]]
name = "elm-json"
path = "src/bin/main.rs"

[profile.release]
lto = true
panic = 'abort'

[patch.crates-io]
isahc = { git = "https://github.com/zwilias/isahc.git", features = ["static-ssl"] }
